language: c++
sudo: false
dist: trusty

compiler:
  - gcc

addons:
  apt:
    packages:
      - libsparsehash-dev
      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j 3 
  - make test

notifications:
  email:
    on_success: never
    on_failure: always
